apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: kubernetes-google-service
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Kubernetes Service
    # source:
    #   repo: https://github.com/GoogleCloudPlatform/google-kubernetes-service-module.git
    #   sourceType: git
    #   dir: /modules/v2
    actuationTool:
      flavor: Kubernetes
      # version: TBD
    description: {}
  interfaces:
    variables:
      - name: name
        description: Name of the service
        varType: string
        required: true
      - name: namespace
        description: Namespace of the service
        varType: string
        required: true
      - name: service_type
        description: Type of the service
        varType: string
        defaultValue: ClusterIP
      - name: selector_deployment_name
        description: Name of the deployment
        varType: string
        connections:
          - source:
              source: Deployment
            spec:
              outputExpr: "{deployment_name}"
      - name: ports
        description: Exposed ports of the service
        varType: |-
          list(object({
            port: number
            target_port: number
            protocol: string
            name: string
          }))
        required: true
        connections:
          - source:
              source: Deployment
            spec:
              outputExpr: "{port: \"80\", target_port: containers.ports.container_port, protocol: \"TCP\", target_name: containers.ports.name}"